<?php if (!isset($now)) $now = new \DateTime(); ?>
<div class="row">
    <div class="span5">...</div>
    <div class="span7">
<?php foreach ( $this->sensors as $sensor ): ?>
        <div class="well">
            <div style="margin: -10px 0 0 -10px;font-size:1.1em;"><?php echo $this->escapeHtml($sensor->getCode()); ?></div>
<img src="<?php echo $this->url('sensor/graph', array('code' => $sensor->getCode())); ?>" />
            <?php $latestReading = $sensor->getLatestReading(); ?>
            <div style="float:right; text-align:center; margin-top:7px">
                <div style="font-size:1.8em;"><?php echo is_null($latestReading) ? '--' : ($this->escapeHtml($latestReading->getValue()).'&deg;'); ?></div>
<?php if(!is_null($latestReading)): ?>
<?php     $elapsed = $now->diff($latestReading->getDateTime()); ?>
                <div style="padding-top:7px;"><?php echo $this->formatDateInterval($elapsed); ?></div>
            </div>
<?php endif; ?>
            <div style="clear:both;"></div>
        </div>
<?php endforeach; ?>
    </div>
</div>
