<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'GreenhouseTest\Mapper\SensorTest'        => __DIR__ . '/tests/GreenhouseTest/Mapper/SensorTest.php',
    'GreenhouseTest\Mapper\SensorReadingTest' => __DIR__ . '/tests/GreenhouseTest/Mapper/SensorReadingTest.php',
    'GreenhouseTest\Bootstrap'                => __DIR__ . '/tests/Bootstrap.php',
    'Greenhouse\Module'                       => __DIR__ . '/Module.php',
    'Greenhouse\Controller\IndexController'   => __DIR__ . '/src/Greenhouse/Controller/IndexController.php',
    'Greenhouse\Entity\SensorReading'         => __DIR__ . '/src/Greenhouse/Entity/SensorReading.php',
    'Greenhouse\Entity\Sensor'                => __DIR__ . '/src/Greenhouse/Entity/Sensor.php',
    'Greenhouse\Mapper\SensorReading'         => __DIR__ . '/src/Greenhouse/Mapper/SensorReading.php',
    'Greenhouse\Mapper\SensorReadingHydrator' => __DIR__ . '/src/Greenhouse/Mapper/SensorReadingHydrator.php',
    'Greenhouse\Mapper\Sensor'                => __DIR__ . '/src/Greenhouse/Mapper/Sensor.php',
    'Greenhouse\Service\Sensor'               => __DIR__ . '/src/Greenhouse/Service/Sensor.php',
);